#
# This is a minimal config. To see all the options available, refer to the
# "extended" directory
#
---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: mongo-sharded-benchmark
spec:
  shardCount: 4
  mongodsPerShardCount: 2
  mongosCount: 2
  configServerCount: 2
  version: 4.4.0-ent
  type: ShardedCluster

  # Before you create this object, you'll need to create a project ConfigMap and a
  # credentials Secret. For instructions on how to do this, please refer to our
  # documentation, here:
  # https://docs.opsmanager.mongodb.com/current/tutorial/install-k8s-operator
  opsManager:
    configMapRef:
      name: mongo-opsmanager-org-config-map
  credentials: mongo-opsmanager-org-secret

  # This flag allows the creation of pods without persistent volumes. This is for
  # testing only, and must not be used in production. 'false' will disable
  # Persistent Volume Claims. The default is 'true'
  persistent: true
  exposedExternally: true
  configSrvPodSpec:
    podTemplate:
      spec:        
        containers:
          - name: mongodb-enterprise-database
            resources:
              limits:
                cpu: "2"
                memory: 1100M
              requests:
                cpu: "1.8"
                memory: 1024M
  shardPodSpec:
    podTemplate:
      spec:        
        containers:
          - name: mongodb-enterprise-database
            resources:
              limits:
                cpu: "4"
                memory: 4000M
              requests:
                cpu: "3.8"
                memory: 3500M

  mongosPodSpec:
    podTemplate:
      spec:        
        containers:
          - name: mongodb-enterprise-database
            resources:
              limits:
                cpu: "3.3"
                memory: 2500M
              requests:
                cpu: "3"
                memory: 2424M
