apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-benchmark-quarkus-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-benchmark-quarkus-client
  template:
    metadata:
      labels:
        app: database-benchmark-quarkus-client
    spec:
      imagePullSecrets:
        - name: private-reg-cred
      containers:
        - name: database-benchmark-container
          image: quay.io/lrangine/database-benchmark-client:2.0.0-SNAPSHOT
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "2"
              memory: 2000Mi
            requests:
              cpu: "1.8"
              memory: 1800Mi
          env:
            - name: MIN_POOL
              value: "10"
            - name: MAX_POOL
              value: "10"
            - name: WORKER_POOL_SIZE
              value: "10"
            - name: quarkus.mongodb.connection-string
              valueFrom:
                secretKeyRef:
                  name: database-benchmark-mongo
                  key: connectionString.standard
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: database-benchmark-quarkus-client
spec:
  selector:
    app: database-benchmark-quarkus-client
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080